#!/usr/bin/env python

import os, sys, re

if len(sys.argv) >= 2:
    base_filename = sys.argv[1]
else:
    base_filename = "hawaii-settings.desktop"
translations = {
    "Name": [],
    "GenericName": [],
    "Comment": [],
    "Keywords": []
}

for filename in os.listdir("translations"):
    f = open(os.path.join("translations", filename), "r")
    for line in f.readlines():
        m = re.match(r'^(Name|GenericName|Comment|Keywords)\[.*\]\s*=(.+)', line)
        if not m:
            continue
        translations[m.group(1)].append(line)
    f.close()

contents = ""
f = open("%s.in" % base_filename, "r")
for line in f.readlines():
    contents += line
    m = re.match('^(Name|GenericName|Comment|Keywords)', line)
    if not m:
        continue
    for entry in translations[m.group(1)]:
        contents += entry
f.close()

f = open(base_filename, "w")
f.write(contents)
f.close()
