# SPDX-FileCopyrightText: 2022 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - master
      - develop

jobs:
  linux-qt6:
    uses: lirios/.github/.github/workflows/build-linux-qt6.yml@master
    with:
      build_dependencies: "qtgsettings fluid libliri"
